name: AWS OIDC Test
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]   # must match your trust policy
 
jobs:
  verify-aws-access:
    runs-on: ubuntu-latest
 
    # Needed so GitHub can issue the OIDC token
    permissions:
      id-token: write
      contents: read
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::027378719919:role/GitHubDeploy-Kiro
          aws-region: us-east-1                                # or your region
 
      - name: Verify caller identity
        run: aws sts get-caller-identity